#DEPLOYMENT YAML
name: dbdump
stack: nextjs
port: 3097
healthPath: /

expose:
  prod:
    mode: ingress
    domain: dbdump.cc
  staging:
    mode: ingress
    domain: dbdump.staging.nameksociety.com

resources:
  cpu:
    request: 100m
    limit: 500m
  memory:
    request: 192Mi
    limit: 512Mi

replicas:
  prod: 1
  staging: 1

config:
  prod:
    NODE_ENV: production
    
  staging:
    NODE_ENV: production